import {
  AssignWorkCenterUserSchema,
  BatchCreateFieldSchema,
  BatchCreateStepSchema,
  BatchUpdateFieldValuesSchema,
  ChangePasswordSchema,
  ClockOutLaborTicketSchema,
  CompleteOrderRunSchema,
  CreateAgentUserSchema,
  CreateFieldRefSchema,
  CreateFieldSchema,
  CreateItemInstanceSchema,
  CreateItemSchema,
  CreateOperationDependencySchema,
  CreateOperationRunCommentSchema,
  CreateOperationSchema,
  CreateOrderRevisionSchema,
  CreateOrderRunSchema,
  CreateOrderSchema,
  CreateStepSchema,
  CreateUserSchema,
  CreateWorkCenterSchema,
  GrantPermissionSchema,
  LoginRequestSchema,
  TransitionNoteSchema,
  UpdateFieldSchema,
  UpdateFieldValueSchema,
  UpdateItemInstanceSchema,
  UpdateItemSchema,
  UpdateOperationRunSchema,
  UpdateOperationSchema,
  UpdateOrderRevisionSchema,
  UpdateOrderRunSchema,
  UpdateOrderSchema,
  UpdateStepSchema,
  UpdateUserSchema,
  UpdateWorkCenterSchema,
} from "@naisys/erp-shared";
import { z } from "zod/v4";
import type { $ZodType } from "zod/v4/core";

export const schemaRegistry: Record<string, $ZodType> = {
  CreateItem: CreateItemSchema,
  UpdateItem: UpdateItemSchema,
  CreateItemInstance: CreateItemInstanceSchema,
  UpdateItemInstance: UpdateItemInstanceSchema,
  CreateOrder: CreateOrderSchema,
  UpdateOrder: UpdateOrderSchema,
  CreateOrderRevision: CreateOrderRevisionSchema,
  UpdateOrderRevision: UpdateOrderRevisionSchema,
  CreateOrderRun: CreateOrderRunSchema,
  UpdateOrderRun: UpdateOrderRunSchema,
  CompleteOrderRun: CompleteOrderRunSchema,
  CreateOperation: CreateOperationSchema,
  CreateFieldRef: CreateFieldRefSchema,
  CreateOperationDependency: CreateOperationDependencySchema,
  UpdateOperation: UpdateOperationSchema,
  TransitionNote: TransitionNoteSchema,
  UpdateOperationRun: UpdateOperationRunSchema,
  CreateOperationRunComment: CreateOperationRunCommentSchema,
  CreateStep: CreateStepSchema,
  BatchCreateStep: BatchCreateStepSchema,
  UpdateStep: UpdateStepSchema,
  CreateField: CreateFieldSchema,
  BatchCreateField: BatchCreateFieldSchema,
  UpdateField: UpdateFieldSchema,
  UpdateFieldValue: UpdateFieldValueSchema,
  BatchUpdateFieldValues: BatchUpdateFieldValuesSchema,
  LoginRequest: LoginRequestSchema,
  CreateUser: CreateUserSchema,
  CreateAgentUser: CreateAgentUserSchema,
  UpdateUser: UpdateUserSchema,
  GrantPermission: GrantPermissionSchema,
  ChangePassword: ChangePasswordSchema,
  ClockOutLaborTicket: ClockOutLaborTicketSchema,
  CreateWorkCenter: CreateWorkCenterSchema,
  UpdateWorkCenter: UpdateWorkCenterSchema,
  AssignWorkCenterUser: AssignWorkCenterUserSchema,
};

// Register schemas with Zod global registry for OpenAPI components/schemas population
for (const [name, schema] of Object.entries(schemaRegistry)) {
  z.globalRegistry.add(schema, { id: name });
}
