import {
  CODEX_REFRESH_TOKEN_VAR,
  CODEX_RESPONSES_BASE_URL,
} from "../auth/codexOAuth.js";
import {
  type ImageModel,
  LlmApiType,
  type LlmModel,
  type LlmReasoningLevel,
} from "./modelTypes.js";

function codexOAuthModel(params: {
  key: string;
  label: string;
  versionName: string;
  reasoningLevel?: LlmReasoningLevel;
  aliases?: string[];
  maxTokens?: number;
}): LlmModel {
  return {
    key: params.key,
    ...(params.aliases?.length ? { aliases: params.aliases } : {}),
    label: params.label,
    versionName: params.versionName,
    baseUrl: CODEX_RESPONSES_BASE_URL,
    apiType: LlmApiType.OpenAIOAuth,
    // Refresh token presence indicates the provider is configured; the
    // access token itself is minted on demand by the hub and never lives
    // in the variable map.
    apiKeyVar: CODEX_REFRESH_TOKEN_VAR,
    maxTokens: params.maxTokens ?? 400_000,
    // Subscription-backed ChatGPT/Codex OAuth is not metered like API-key usage.
    inputCost: 0,
    outputCost: 0,
    cacheWriteCost: 0,
    cacheReadCost: 0,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    reasoningLevel: params.reasoningLevel,
  };
}

// --- Built-in LLM models ---
// Prices are per 1M tokens in USD (standard, short-context rates).
// Last verified: September 18, 2026. Keep existing keys stable for agent configs.

export const builtInLlmModels: LlmModel[] = [
  {
    key: LlmApiType.None,
    label: "None",
    versionName: LlmApiType.None,
    apiType: LlmApiType.None,
    apiKeyVar: "",
    maxTokens: 10_000,
    inputCost: 0,
    outputCost: 0,
  },
  {
    key: LlmApiType.Mock,
    label: "Mock",
    versionName: LlmApiType.Mock,
    apiType: LlmApiType.Mock,
    apiKeyVar: "",
    maxTokens: 10_000,
    inputCost: 0,
    outputCost: 0,
  },

  {
    key: "lmstudio",
    label: "LM Studio",
    versionName: "qwen/qwen3.5-9b",
    baseUrl: "http://127.0.0.1:1234/v1",
    apiType: LlmApiType.OpenAICompatible,
    apiKeyVar: "",
    maxTokens: 100_000,
    inputCost: 0,
    outputCost: 0,
  },

  // ── xAI / Grok ──────────────────────────────────────────────────────
  // https://docs.x.ai/developers/models
  {
    key: "grok",
    aliases: ["grok4"],
    label: "Grok",
    versionName: "grok-4.6",
    baseUrl: "https://api.x.ai/v1",
    apiType: LlmApiType.OpenAICompatible,
    apiKeyVar: "XAI_API_KEY",
    maxTokens: 500_000,
    inputCost: 2,
    outputCost: 6,
    cacheWriteCost: 2,
    cacheReadCost: 0.5,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    reasoningLevel: "medium",
  },
  {
    key: "grok_fast",
    aliases: ["grok4fast"],
    label: "Grok Fast",
    versionName: "grok-4.3",
    baseUrl: "https://api.x.ai/v1",
    apiType: LlmApiType.OpenAICompatible,
    apiKeyVar: "XAI_API_KEY",
    maxTokens: 1_000_000,
    inputCost: 1.25,
    outputCost: 2.5,
    cacheWriteCost: 1.25,
    cacheReadCost: 0.2,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    reasoningLevel: "medium",
  },

  // ── OpenAI Models ────────────────────────────────────────────────────
  // https://developers.openai.com/api/docs/pricing
  // GPT-5.6+ cache writes are 1.25x input; cache retention is 30 minutes.
  {
    key: "gpt_astra",
    label: "GPT Astra",
    versionName: "gpt-6-astra",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 1_050_000,
    inputCost: 10,
    outputCost: 50,
    cacheWriteCost: 12.5,
    cacheReadCost: 1,
    cacheTtlSeconds: 1800,
    supportsToolUse: true,
    supportsVision: true,
    supportsComputerUse: true,
    reasoningLevel: "medium",
  },
  {
    key: "gpt_sol",
    aliases: ["gpt5"],
    label: "GPT Sol",
    versionName: "gpt-5.6-sol",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 1_050_000,
    inputCost: 4,
    outputCost: 20,
    cacheWriteCost: 5,
    cacheReadCost: 0.4,
    cacheTtlSeconds: 1800,
    supportsToolUse: true,
    supportsVision: true,
    supportsComputerUse: true,
    reasoningLevel: "medium",
  },
  {
    key: "gpt_terra",
    label: "GPT Terra",
    versionName: "gpt-5.6-terra",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 1_050_000,
    inputCost: 2,
    outputCost: 12,
    cacheWriteCost: 2.5,
    cacheReadCost: 0.2,
    cacheTtlSeconds: 1800,
    supportsToolUse: true,
    supportsVision: true,
    supportsComputerUse: true,
    reasoningLevel: "medium",
  },
  {
    key: "gpt_luna",
    label: "GPT Luna",
    versionName: "gpt-5.6-luna",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 1_050_000,
    inputCost: 0.2,
    outputCost: 1.2,
    cacheWriteCost: 0.25,
    cacheReadCost: 0.02,
    cacheTtlSeconds: 1800,
    supportsToolUse: true,
    supportsVision: true,
    supportsComputerUse: true,
    reasoningLevel: "medium",
  },
  // Preserve the cheaper, explicitly selected legacy tiers in existing agents.
  {
    key: "gpt_mini",
    aliases: ["gpt5mini"],
    label: "GPT Mini",
    versionName: "gpt-5-mini",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 400_000,
    inputCost: 0.25,
    outputCost: 2,
    cacheWriteCost: 0.25,
    cacheReadCost: 0.025,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    reasoningLevel: "medium",
  },
  {
    key: "gpt_nano",
    aliases: ["gpt5nano"],
    label: "GPT Nano",
    versionName: "gpt-5-nano",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 400_000,
    inputCost: 0.05,
    outputCost: 0.4,
    cacheWriteCost: 0.05,
    cacheReadCost: 0.005,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    reasoningLevel: "medium",
  },
  // OAuth uses the Codex catalog's default context window, distinct from API limits.
  codexOAuthModel({
    key: "gpt_astra_oauth",
    label: "GPT Astra (OAuth)",
    versionName: "gpt-6-astra",
    maxTokens: 272_000,
    reasoningLevel: "medium",
  }),
  codexOAuthModel({
    key: "gpt_sol_oauth",
    label: "GPT Sol (OAuth)",
    versionName: "gpt-5.6-sol",
    aliases: ["gpt52oauth"],
    maxTokens: 272_000,
    reasoningLevel: "medium",
  }),
  codexOAuthModel({
    key: "gpt_terra_oauth",
    label: "GPT Terra (OAuth)",
    versionName: "gpt-5.6-terra",
    aliases: ["gpt5oauth"],
    maxTokens: 272_000,
    reasoningLevel: "medium",
  }),
  codexOAuthModel({
    key: "gpt_luna_oauth",
    label: "GPT Luna (OAuth)",
    versionName: "gpt-5.6-luna",
    aliases: ["gpt54minioauth"],
    maxTokens: 272_000,
    reasoningLevel: "medium",
  }),
  // Still works with this account; keep this explicit pin until retirement.
  codexOAuthModel({
    key: "gpt55oauth",
    label: "GPT 5.5 (Legacy OAuth)",
    versionName: "gpt-5.5",
    reasoningLevel: "medium",
  }),

  // ── Google Models ────────────────────────────────────────────────────
  // https://ai.google.dev/gemini-api/docs/pricing
  {
    key: "gemini_pro",
    aliases: ["gemini3pro"],
    label: "Gemini Pro",
    versionName: "gemini-3.1-pro-preview",
    apiType: LlmApiType.Google,
    apiKeyVar: "GOOGLE_API_KEY",
    maxTokens: 1_048_576,
    inputCost: 2.0,
    outputCost: 12.0,
    cacheWriteCost: 0.2,
    cacheReadCost: 0.2,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    supportsHearing: true,
    reasoningLevel: "medium",
  },
  {
    key: "gemini_flash",
    aliases: ["gemini3flash"],
    label: "Gemini Flash",
    versionName: "gemini-3.8-flash",
    apiType: LlmApiType.Google,
    apiKeyVar: "GOOGLE_API_KEY",
    maxTokens: 1_048_576,
    // Introductory prices through 2026-12-31; double starting 2027-01-01.
    inputCost: 0.75,
    outputCost: 3.75,
    cacheWriteCost: 0.75,
    cacheReadCost: 0.075,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    supportsHearing: true,
    supportsComputerUse: true,
    reasoningLevel: "medium",
  },
  {
    key: "gemini_computer_use",
    aliases: ["gemini2pro"],
    label: "Gemini Computer Use (Preview)",
    versionName: "gemini-2.5-computer-use-preview-10-2025",
    apiType: LlmApiType.Google,
    apiKeyVar: "GOOGLE_API_KEY",
    maxTokens: 131_072,
    // Introductory prices through 2026-12-31; double starting 2027-01-01.
    inputCost: 1,
    outputCost: 5,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    supportsComputerUse: true,
    reasoningLevel: "medium",
  },

  // ── Anthropic Models ─────────────────────────────────────────────────
  // https://platform.claude.com/docs/en/about-claude/pricing
  // Cache: 5m write = 1.25x input, read = 0.1x input.
  {
    key: "claude_opus",
    aliases: ["claude4opus"],
    label: "Claude Opus",
    versionName: "claude-opus-5",
    apiType: LlmApiType.Anthropic,
    apiKeyVar: "ANTHROPIC_API_KEY",
    maxTokens: 1_000_000,
    inputCost: 5,
    outputCost: 25,
    cacheWriteCost: 6.25,
    cacheReadCost: 0.5,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    supportsComputerUse: true,
    reasoningLevel: "medium",
  },
  {
    key: "claude_sonnet",
    aliases: ["claude4sonnet"],
    label: "Claude Sonnet",
    versionName: "claude-sonnet-5",
    apiType: LlmApiType.Anthropic,
    apiKeyVar: "ANTHROPIC_API_KEY",
    maxTokens: 1_000_000,
    inputCost: 2,
    outputCost: 10,
    cacheWriteCost: 2.5,
    cacheReadCost: 0.2,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    supportsComputerUse: true,
    reasoningLevel: "medium",
  },
  {
    key: "claude_haiku",
    aliases: ["claude4haiku"],
    label: "Claude Haiku",
    versionName: "claude-haiku-4-5",
    apiType: LlmApiType.Anthropic,
    apiKeyVar: "ANTHROPIC_API_KEY",
    maxTokens: 200_000,
    inputCost: 1,
    outputCost: 5,
    cacheWriteCost: 1.25,
    cacheReadCost: 0.1,
    cacheTtlSeconds: 300,
    supportsToolUse: true,
    supportsVision: true,
    supportsComputerUse: true,
    reasoningLevel: "medium",
  },
];

// --- Built-in image models ---
// Costs are approximate per-image for 1024x1024.

export const builtInImageModels: ImageModel[] = [
  {
    key: "gpt_image_high",
    aliases: ["gptimage1high"],
    label: "GPT Image High",
    versionName: "gpt-image-1.5",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    quality: "high",
    cost: 0.17,
  },
  {
    key: "gpt_image_medium",
    aliases: ["gptimage1medium"],
    label: "GPT Image Medium",
    versionName: "gpt-image-1.5",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    quality: "medium",
    cost: 0.04,
  },
  {
    key: "gpt_image_low",
    aliases: ["gptimage1low"],
    label: "GPT Image Low",
    versionName: "gpt-image-1.5",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    quality: "low",
    cost: 0.01,
  },
  {
    key: "dalle_1024_hd",
    aliases: ["dalle3-1024-HD"],
    label: "DALL-E 1024 HD",
    versionName: "dall-e-3",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    quality: "hd",
    cost: 0.08,
  },
  {
    key: "dalle_1024",
    aliases: ["dalle3-1024"],
    label: "DALL-E 1024",
    versionName: "dall-e-3",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    cost: 0.04,
  },
];
