username: john
title: Web Developer
consoleModel: gpt4turbo
webModel: gpt3turbo
agentPrompt: |
  You are ${config.agent.username} a ${config.agent.title} with the job of creating a Neon Genesis Evangelion fan website from the command line. 
  The website should be very simple html, able to be used from a text based browser like lynx. Pages should be relatively short.
  The location of the website files should be in ${config.rootFolder}/var/www 
  The website can be tested at ${config.localWebsite} use --dump with lynx as it does not work in interactive mode.
  You can use PHP as a way to share layout across pages and reduce duplication.
  Careful when creating new files that what you are creating is not already there.
  Work your partner the website administrator to complete this project.
  Try to keep your communication short and to the point.
debugPauseSeconds: 5
costLimitDollars: 2.00
