import { LlmApiType, type ImageModel, type LlmModel } from "./modelTypes.js";

// --- Built-in LLM models ---
// Prices are per 1M tokens in USD. Last updated: February 2026.

export const builtInLlmModels: LlmModel[] = [
  {
    key: LlmApiType.None,
    label: "None",
    versionName: LlmApiType.None,
    apiType: LlmApiType.None,
    apiKeyVar: "",
    maxTokens: 10_000,
    inputCost: 0,
    outputCost: 0,
  },
  {
    key: LlmApiType.Mock,
    label: "Mock",
    versionName: LlmApiType.Mock,
    apiType: LlmApiType.Mock,
    apiKeyVar: "",
    maxTokens: 10_000,
    inputCost: 0,
    outputCost: 0,
  },

  // ── Open Router ──────────────────────────────────────────────────────
  {
    key: "llama4",
    label: "Llama 4 Maverick",
    versionName: "meta-llama/llama-4-maverick",
    baseUrl: "https://openrouter.ai/api/v1",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENROUTER_API_KEY",
    maxTokens: 1_000_000,
    inputCost: 0.15,
    outputCost: 0.6,
    supportsVision: true,
  },

  // ── xAI / Grok ──────────────────────────────────────────────────────
  // https://docs.x.ai/developers/models
  {
    key: "grok4",
    label: "Grok 4",
    versionName: "grok-4",
    baseUrl: "https://api.x.ai/v1",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "XAI_API_KEY",
    maxTokens: 256_000,
    inputCost: 3,
    outputCost: 15,
    cacheWriteCost: 0.75,
    cacheReadCost: 0.75,
    supportsVision: true,
  },
  {
    key: "grok4fast",
    label: "Grok 4.1 Fast",
    versionName: "grok-4.1-fast",
    baseUrl: "https://api.x.ai/v1",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "XAI_API_KEY",
    maxTokens: 2_000_000,
    inputCost: 0.2,
    outputCost: 0.5,
    cacheWriteCost: 0.05,
    cacheReadCost: 0.05,
    supportsVision: true,
  },

  // ── OpenAI Models ────────────────────────────────────────────────────
  // https://openai.com/api/pricing/
  {
    key: "gpt5",
    label: "GPT 5.2",
    versionName: "gpt-5.2",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 400_000,
    inputCost: 1.75,
    outputCost: 14.0,
    cacheWriteCost: 0.18,
    cacheReadCost: 0.18,
    supportsVision: true,
    supportsHearing: true,
  },
  {
    key: "gpt5mini",
    label: "GPT 5 Mini",
    versionName: "gpt-5-mini",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 400_000,
    inputCost: 0.25,
    outputCost: 2.0,
    cacheWriteCost: 0.025,
    cacheReadCost: 0.025,
    supportsVision: true,
    supportsHearing: true,
  },
  {
    key: "gpt5nano",
    label: "GPT 5 Nano",
    versionName: "gpt-5-nano",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 400_000,
    inputCost: 0.05,
    outputCost: 0.4,
    cacheWriteCost: 0.005,
    cacheReadCost: 0.005,
    supportsVision: true,
    supportsHearing: true,
  },

  // ── Google Models ────────────────────────────────────────────────────
  // https://ai.google.dev/gemini-api/docs/pricing
  {
    key: "gemini3pro",
    label: "Gemini 3.1 Pro",
    versionName: "gemini-3.1-pro-preview",
    apiType: LlmApiType.Google,
    apiKeyVar: "GOOGLE_API_KEY",
    maxTokens: 2_000_000,
    inputCost: 2.0,
    outputCost: 12.0,
    cacheWriteCost: 0.2,
    cacheReadCost: 0.2,
    supportsVision: true,
    supportsHearing: true,
  },
  {
    key: "gemini3flash",
    label: "Gemini 3 Flash",
    versionName: "gemini-3-flash-preview",
    apiType: LlmApiType.Google,
    apiKeyVar: "GOOGLE_API_KEY",
    maxTokens: 1_000_000,
    inputCost: 0.5,
    outputCost: 3.0,
    cacheWriteCost: 0.05,
    cacheReadCost: 0.05,
    supportsVision: true,
    supportsHearing: true,
  },

  // ── Anthropic Models ─────────────────────────────────────────────────
  // https://platform.claude.com/docs/en/about-claude/pricing
  // Cache: 5m write = 1.25× input, read = 0.1× input
  {
    key: "claude4opus",
    label: "Claude Opus 4.6",
    versionName: "claude-opus-4-6",
    apiType: LlmApiType.Anthropic,
    apiKeyVar: "ANTHROPIC_API_KEY",
    maxTokens: 200_000,
    inputCost: 5,
    outputCost: 25,
    cacheWriteCost: 6.25,
    cacheReadCost: 0.5,
    supportsVision: true,
  },
  {
    key: "claude4sonnet",
    label: "Claude Sonnet 4.6",
    versionName: "claude-sonnet-4-6",
    apiType: LlmApiType.Anthropic,
    apiKeyVar: "ANTHROPIC_API_KEY",
    maxTokens: 200_000,
    inputCost: 3,
    outputCost: 15,
    cacheWriteCost: 3.75,
    cacheReadCost: 0.3,
    supportsVision: true,
  },
  {
    key: "claude4haiku",
    label: "Claude Haiku 4.5",
    versionName: "claude-haiku-4-5",
    apiType: LlmApiType.Anthropic,
    apiKeyVar: "ANTHROPIC_API_KEY",
    maxTokens: 200_000,
    inputCost: 1,
    outputCost: 5,
    cacheWriteCost: 1.25,
    cacheReadCost: 0.1,
    supportsVision: true,
  },
];

// --- Built-in image models ---
// Costs are approximate per-image for 1024x1024.

export const builtInImageModels: ImageModel[] = [
  {
    key: "gptimage1high",
    label: "GPT Image 1.5 High",
    versionName: "gpt-image-1.5",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    quality: "high",
    cost: 0.17,
  },
  {
    key: "gptimage1medium",
    label: "GPT Image 1.5 Medium",
    versionName: "gpt-image-1.5",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    quality: "medium",
    cost: 0.04,
  },
  {
    key: "gptimage1low",
    label: "GPT Image 1.5 Low",
    versionName: "gpt-image-1.5",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    quality: "low",
    cost: 0.01,
  },
  {
    key: "dalle3-1024-HD",
    label: "DALL-E 3 1024 HD",
    versionName: "dall-e-3",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    quality: "hd",
    cost: 0.08,
  },
  {
    key: "dalle3-1024",
    label: "DALL-E 3 1024",
    versionName: "dall-e-3",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    cost: 0.04,
  },
];
