import { LlmApiType, type LlmModel, type ImageModel } from "./modelTypes.js";

// --- Built-in LLM models ---

export const builtInLlmModels: LlmModel[] = [
  {
    key: LlmApiType.None,
    label: "None",
    versionName: LlmApiType.None,
    apiType: LlmApiType.None,
    apiKeyVar: "",
    maxTokens: 10_000,
    inputCost: 0,
    outputCost: 0,
  },
  {
    key: LlmApiType.Mock,
    label: "Mock",
    versionName: LlmApiType.Mock,
    apiType: LlmApiType.Mock,
    apiKeyVar: "",
    maxTokens: 10_000,
    inputCost: 0,
    outputCost: 0,
  },
  // Open Router
  {
    key: "llama3-405b",
    label: "Llama 3.1 405B",
    versionName: "meta-llama/llama-3.1-405b-instruct",
    baseUrl: "https://openrouter.ai/api/v1",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENROUTER_API_KEY",
    maxTokens: 128_000,
    inputCost: 2.7,
    outputCost: 2.7,
  },
  // Grok
  {
    key: "grok4",
    label: "Grok 4",
    versionName: "grok-4",
    baseUrl: "https://api.x.ai/v1",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "XAI_API_KEY",
    maxTokens: 256_000,
    inputCost: 3,
    outputCost: 15,
    cacheWriteCost: 0.75,
    cacheReadCost: 0.75,
    supportsVision: true,
  },
  {
    key: "grok4fast",
    label: "Grok 4 Fast",
    versionName: "grok-4-fast",
    baseUrl: "https://api.x.ai/v1",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "XAI_API_KEY",
    maxTokens: 2_000_000,
    inputCost: 0.2,
    outputCost: 0.5,
    cacheWriteCost: 0.05,
    cacheReadCost: 0.05,
    supportsVision: true,
  },
  // OpenAI Models
  // https://openai.com/api/pricing/
  {
    key: "gpt5",
    label: "GPT 5.1",
    versionName: "gpt-5.1",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 400_000,
    inputCost: 1.25,
    outputCost: 10.0,
    cacheWriteCost: 0.125,
    cacheReadCost: 0.125,
    supportsVision: true,
  },
  {
    key: "gpt5mini",
    label: "GPT 5 Mini",
    versionName: "gpt-5-mini",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 400_000,
    inputCost: 0.25,
    outputCost: 2.0,
    cacheWriteCost: 0.025,
    cacheReadCost: 0.025,
    supportsVision: true,
  },
  {
    key: "gpt5nano",
    label: "GPT 5 Nano",
    versionName: "gpt-5-nano",
    apiType: LlmApiType.OpenAI,
    apiKeyVar: "OPENAI_API_KEY",
    maxTokens: 400_000,
    inputCost: 0.05,
    outputCost: 0.4,
    cacheWriteCost: 0.005,
    cacheReadCost: 0.005,
    supportsVision: true,
  },
  // Google Models
  {
    key: "gemini3pro",
    label: "Gemini 3 Pro",
    versionName: "gemini-3-pro-image-preview",
    apiType: LlmApiType.Google,
    apiKeyVar: "GOOGLE_API_KEY",
    maxTokens: 2_000_000,
    inputCost: 2.0,
    outputCost: 12.0,
    cacheWriteCost: 0.2,
    cacheReadCost: 0.2,
    supportsVision: true,
  },
  {
    key: "gemini2.5pro",
    label: "Gemini 2.5 Pro",
    versionName: "gemini-2.5-pro",
    apiType: LlmApiType.Google,
    apiKeyVar: "GOOGLE_API_KEY",
    maxTokens: 2_000_000,
    inputCost: 1.25,
    outputCost: 10.0,
    cacheWriteCost: 0.125,
    cacheReadCost: 0.125,
    supportsVision: true,
  },
  {
    key: "gemini2.5flash",
    label: "Gemini 2.5 Flash",
    versionName: "gemini-2.5-flash",
    apiType: LlmApiType.Google,
    apiKeyVar: "GOOGLE_API_KEY",
    maxTokens: 1_000_000,
    inputCost: 0.3,
    outputCost: 2.5,
    cacheWriteCost: 0.03,
    cacheReadCost: 0.03,
    supportsVision: true,
  },
  {
    key: "gemini2.5flashlite",
    label: "Gemini 2.5 Flash Lite",
    versionName: "gemini-2.5-flash-lite",
    apiType: LlmApiType.Google,
    apiKeyVar: "GOOGLE_API_KEY",
    maxTokens: 1_000_000,
    inputCost: 0.1,
    outputCost: 0.4,
    cacheWriteCost: 0.01,
    cacheReadCost: 0.01,
    supportsVision: true,
  },
  // Anthropic Models
  {
    key: "claude4opus",
    label: "Claude 4 Opus",
    versionName: "claude-opus-4-20250514",
    apiType: LlmApiType.Anthropic,
    apiKeyVar: "ANTHROPIC_API_KEY",
    maxTokens: 200_000,
    inputCost: 15,
    outputCost: 75,
    cacheWriteCost: 18.75,
    cacheReadCost: 1.5,
    supportsVision: true,
  },
  {
    key: "claude4sonnet",
    label: "Claude 4 Sonnet",
    versionName: "claude-sonnet-4-5-20250929",
    apiType: LlmApiType.Anthropic,
    apiKeyVar: "ANTHROPIC_API_KEY",
    maxTokens: 200_000,
    inputCost: 3,
    outputCost: 15,
    cacheWriteCost: 3.75,
    cacheReadCost: 0.3,
    supportsVision: true,
  },
  {
    key: "claude4haiku",
    label: "Claude 4 Haiku",
    versionName: "claude-haiku-4-5-20251001",
    apiType: LlmApiType.Anthropic,
    apiKeyVar: "ANTHROPIC_API_KEY",
    maxTokens: 200_000,
    inputCost: 1,
    outputCost: 5,
    cacheWriteCost: 1.25,
    cacheReadCost: 0.1,
    supportsVision: true,
  },
];

// --- Built-in image models ---

export const builtInImageModels: ImageModel[] = [
  {
    key: "dalle3-1024-HD",
    label: "DALL-E 3 1024 HD",
    versionName: "dall-e-3",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    quality: "hd",
    cost: 0.08,
  },
  {
    key: "dalle3-1024",
    label: "DALL-E 3 1024",
    versionName: "dall-e-3",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    cost: 0.04,
  },
  {
    key: "dalle2-1024",
    label: "DALL-E 2 1024",
    versionName: "dall-e-2",
    size: "1024x1024",
    apiKeyVar: "OPENAI_API_KEY",
    cost: 0.02,
  },
  {
    key: "dalle2-512",
    label: "DALL-E 2 512",
    versionName: "dall-e-2",
    size: "512x512",
    apiKeyVar: "OPENAI_API_KEY",
    cost: 0.018,
  },
  {
    key: "dalle2-256",
    label: "DALL-E 2 256",
    versionName: "dall-e-2",
    size: "256x256",
    apiKeyVar: "OPENAI_API_KEY",
    cost: 0.016,
  },
];
