export const OPENAI_CODEX_RESPONSES_BASE_URL =
  "https://chatgpt.com/backend-api/codex";

export const OPENAI_CODEX_ACCESS_TOKEN_VAR = "OPENAI_CODEX_ACCESS_TOKEN";
export const OPENAI_CODEX_REFRESH_TOKEN_VAR = "OPENAI_CODEX_REFRESH_TOKEN";
export const OPENAI_CODEX_EXPIRES_AT_VAR = "OPENAI_CODEX_EXPIRES_AT";

export const openAiCodexOAuthEnvVars = [
  OPENAI_CODEX_ACCESS_TOKEN_VAR,
  OPENAI_CODEX_REFRESH_TOKEN_VAR,
  OPENAI_CODEX_EXPIRES_AT_VAR,
] as const;
